@startuml
!include ./../no.ks.fiks.plan.v2.felles.arealformaalomraade/arealformaalomraade.pu

class HentReguleringsformaalResultat {
    +arealformaalOmraade: ArealformaalOmraade [0..1]
}

HentReguleringsformaalResultat -- "[0..1]" ArealformaalOmraade


@enduml