@startuml
!include ./../no.ks.fiks.plan.v2.felles.dokument/dokument.pu

class HentGjeldendePlandokumenterResultat {
    +plandokumenter: Dokument[]
}

HentGjeldendePlandokumenterResultat -- Dokument

@enduml