@startuml
class Dokument {
    +tittel: string
    +dokumenttype: Dokumenttype
    +referanseDokumentfil: ReferanseDokumentfil
    +mimetype: string
    +dokumentsdato: date
    +arkivnavn: string
}

Dokument -- Dokumenttype
Dokument -- ReferanseDokumentfil

class Dokumenttype <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

class ReferanseDokumentfil {
    +id: string
    +url: string
}

@enduml