@startuml
class Posisjon {
    +type: PosisjonType
    +koordinater: number[]
    +koordinatsystem: Koordinatsystem
}

Posisjon -- Koordinatsystem
Posisjon -- PosisjonType

class Koordinatsystem <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

enum PosisjonType {
    Point
}

@enduml