@startuml

class OpprettArealplan {
    +plannavn: string
    +plantype: Plantype
    +planstatus: Planstatus
    +lovreferanse: Lovreferanse
    +saksnummer: Saksnummer
    +forslagstillertype: ForslagstillerType
}

class Plantype <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

class Planstatus <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

class Lovreferanse <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

class ForslagstillerType <<Kode>>{
    +kodeverdi: string
    +kodebeskrivelse: string
}

OpprettArealplan -- Plantype
OpprettArealplan -- Planstatus
OpprettArealplan -- Lovreferanse
OpprettArealplan -- ForslagstillerType
OpprettArealplan -- Saksnummer

note top of Saksnummer : Se detaljer i diagram for skjema 'no.ks.fiks.plan.v2.felles.saksnummer'

@enduml