@startuml
class Flate {
    +type: FlateType
    +koordinater: Koordinat[]
    +koordinatsystem: Koordinatsystem
}

Flate -- FlateType
Flate -- Koordinat
Flate -- Koordinatsystem

enum FlateType {
    Polygon
}

class Koordinat {
    +items: number[]
}

class Koordinatsystem <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

@enduml