@startuml
!include ./../no.ks.fiks.plan.v2.felles.nasjonalarealplanid/nasjonalarealplanid.pu

class HentReguleringsformaal {
    +nasjonalArealplanId: NasjonalArealplanId
}

HentReguleringsformaal -- NasjonalArealplanId

@enduml