@startuml
class Dokument {
    +id: string
    +tittel: string
    +filnavn: string
    +dokumenttype: Dokumenttype
    +referanseDokumentfil: string
    +mimetype: string
    +dokumentsdato: date
    +arkivnavn: string
}

Dokument -- Dokumenttype

class Dokumenttype <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

@enduml