@startuml

Fagsystem -> Planregister: no.ks.fiks.plan.v2.innsyn.arealplan.hent

alt Hent arealplan ok
...resultat-melding med innhold...

Fagsystem <- Planregister: no.ks.fiks.plan.v2.innsyn.arealplan.hent.resultat

else Feil: planregister fant ikke arealplan
...feil-melding med innhold...

Fagsystem <- Planregister: no.ks.fiks.plan.v2.feilmelding.ikkefunnet

else Feil: hent-meldingen var ikke korrekt
...feil-melding med innhold...

Fagsystem <- Planregister: no.ks.fiks.plan.v2.feilmelding.ugyldigforespoersel

else Feil: planregister fikk serverfeil
...feil-melding med innhold...

Fagsystem <- Planregister: no.ks.fiks.plan.v2.feilmelding.serverfeil

end
@enduml