@startuml
!include ./../no.ks.fiks.plan.v2.felles.flate/flate.pu
!include ./../no.ks.fiks.plan.v2.felles.nasjonalarealplanid/nasjonalarealplanid.pu

class RegistrerPlanomraade {
    +nasjonalArealplanId: NasjonalArealplanId
    +planomraade: Planomraade
}

class Planomraade {
    +omraade: Omraade
    +vertikalnivaa: Vertikalnivaa
}

class Omraade {
    +ytreAvgrensning: Flate
    +indreAvgrensninger: Flate[]
}

enum Vertikalnivaa {
    Under grunnen
    På grunnen/vannoverflate
    Over grunnen (bru)
    På bunnen (vann/sjoe)
    I vannsoeylen
}

RegistrerPlanomraade -- Planomraade
RegistrerPlanomraade -- NasjonalArealplanId
Planomraade -- Omraade
Planomraade -- Vertikalnivaa
Omraade -- Flate

@enduml