@startuml

class OppdaterDispensasjon {
    +dispensasjon: Dispensasjon
    +opphevIdentifikasjon: string
    +begrunnelse: string
    +referanseKlageSaksnummer: ReferanseKlageSaksnummer
    +plandokumenter: Dokument[]
    +forslagstillertype: Forslagstillertype
    +vedlegg: Dokument[]
}

class ReferanseKlageSaksnummer {
    +saksaar: integer
    +sakssekvensnummer: integer
}

class ForslagstillerType <<Kode>>{
    +kodeverdi: string
    +kodebeskrivelse: string
}

OppdaterDispensasjon -- ForslagstillerType
OppdaterDispensasjon -- Dispensasjon
OppdaterDispensasjon -- Dokument
OppdaterDispensasjon -- ReferanseKlageSaksnummer

note top of Dispensasjon : Se detaljer i diagram for skjema 'no.ks.fiks.plan.v2.felles.dispensasjon'
note top of Dokument : Se detaljer i diagram for skjema 'no.ks.fiks.plan.v2.felles.dokument'

@enduml