@startuml
!include ./../no.ks.fiks.plan.v2.felles.nasjonalarealplanid/nasjonalarealplanid.pu

class HentRestriksjoner {
    +nasjonalArealplanId: NasjonalArealplanId
}

HentRestriksjoner -- NasjonalArealplanId

@enduml