@startuml
class Dispensasjon {
    +identifikasjon: string
    +dispensasjonType: DispensasjonType
    +dispensasjonFra: DispensasjonFra
    +nasjonalArealplanId: NasjonalArealplanId
    +begrunnelse: string
    +vedtaksdato:  date
    +posisjon: Posisjon
    +vertikalnivaa: Vertikalnivaa
    +beskrivelse: string
    +innvilgetDispensasjon: boolean
    +saksnummer: Saksnummer
    +varigDispensasjon: boolean
    +varighetFra: date
    +varighetTil: date
    +plandokumenter: Dokument[]
}

Dispensasjon -- DispensasjonType
Dispensasjon -- DispensasjonFra
Dispensasjon -- Vertikalnivaa
Dispensasjon -- NasjonalArealplanId
Dispensasjon -- Posisjon
Dispensasjon -- Saksnummer
Dispensasjon -- Dokument

class DispensasjonType <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

class DispensasjonFra <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

class Vertikalnivaa <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

@enduml