@startuml
!include ./../no.ks.fiks.plan.v2.felles.nasjonalarealplanid/nasjonalarealplanid.pu
!include ./../no.ks.fiks.plan.v2.felles.posisjon/posisjon.pu
!include ./../no.ks.fiks.plan.v2.felles.saksnummer/saksnummer.pu
!include ./../no.ks.fiks.plan.v2.felles.dokument/dokument.pu

class Dispensasjon {
    +identifikasjon: string
    +dispensasjonsType: DispensasjonsType
    +dispensasjonFraLovverk: DispensasjonFraLovverk
    +dispFra: string
    +nasjonalArealplanId: NasjonalArealplanId
    +begrunnelse: string
    +vedtaksdato:  date
    +posisjon: Posisjon
    +vertikalnivaa: Vertikalnivaa
    +beskrivelse: string
    +innvilgetDispensasjon: boolean
    +saksnummer: Saksnummer
    +varigDispensasjon: boolean
    +varighetFra: date
    +varighetTil: date
    +plandokumenter: Dokument[]
}

note left of Dispensasjon::dispensasjonsType
    dispensasjonsType er hentet fra Planregister
end note 

note left of Dispensasjon::DispensasjonFraLovverk 
    dispensasajonFraLovverk: se kodelisten dispensasjonfralovverk.
    Opprinnelig hentet fra eByggesak
end note

note left of Dispensasjon::dispFra 
    Et tekstfelt. Nytt i issue113 og hentet fra planregister 
end note

Dispensasjon -- DispensasjonsType
Dispensasjon -- DispensasjonFraLovverk
Dispensasjon -- Vertikalnivaa
Dispensasjon -- NasjonalArealplanId
Dispensasjon -- Posisjon
Dispensasjon -- Saksnummer
Dispensasjon -- Dokument

class DispensasjonsType <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

class DispensasjonFraLovverk <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

class Vertikalnivaa <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

@enduml