@startuml
!include ./../no.ks.fiks.plan.v2.felles.nasjonalarealplanid/nasjonalarealplanid.pu

class HentGjeldendePlandokumenter {
    +nasjonalArealplanId: NasjonalArealplanId
}

HentGjeldendePlandokumenter -- NasjonalArealplanId

@enduml