@startuml

class OppdaterArealplan {
    +nasjonalArealplanId: NasjonalArealplanId
    +plannavn: string
    +plantype: Plantype
    +planstatus: Planstatus
    +lovreferanse: Lovreferanse
    +saksnummer: Saksnummer
    +forslagstillertype: ForslagstillerType
    +vedlegg: Dokument[]
}

class Plantype <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

class Planstatus <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

class Lovreferanse <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

class ForslagstillerType <<Kode>>{
    +kodeverdi: string
    +kodebeskrivelse: string
}

OppdaterArealplan -- NasjonalArealplanId
OppdaterArealplan -- Plantype
OppdaterArealplan -- Planstatus
OppdaterArealplan -- Lovreferanse
OppdaterArealplan -- ForslagstillerType
OppdaterArealplan -- Saksnummer
OppdaterArealplan -- Dokument

note top of NasjonalArealplanId : Se detaljer i diagram for skjema 'no.ks.fiks.plan.v2.felles.nasjonalarealplanid'
note top of Saksnummer : Se detaljer i diagram for skjema 'no.ks.fiks.plan.v2.felles.saksnummer'
note top of Dokument : Se detaljer i diagram for skjema 'no.ks.fiks.plan.v2.felles.dokument'

@enduml