@startuml

!include ./../no.ks.fiks.plan.v2.felles.arealplan/arealplan.pu
!include ./../no.ks.fiks.plan.v2.felles.planbehandling/planbehandling.pu

class HentArealplanResultat {
    +arealplan: Arealplan
    +planbehandlinger: Planbehandling[]
}

HentArealplanResultat -- Arealplan
HentArealplanResultat -- Planbehandling

@enduml