@startuml
!include ./../no.ks.fiks.plan.v2.felles.saksnummer/saksnummer.pu
!include ./../no.ks.fiks.plan.v2.felles.posisjon/posisjon.pu
!include ./../no.ks.fiks.plan.v2.felles.dokument/dokument.pu

class Planbehandling {
    +posisjon: Posisjon
    +dato: date
    +saksnummer: Saksnummer
    +planbehandlingstype: Planbehandlingstype
    +navn: string
    +plandokumenter: Dokument[]
}

Planbehandling -- Posisjon
Planbehandling -- Saksnummer
Planbehandling -- Planbehandlingstype
Planbehandling -- Dokument

class Planbehandlingstype <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

@enduml