@startuml
!include ./../no.ks.fiks.plan.v2.felles.nasjonalarealplanid/nasjonalarealplanid.pu

class FinnPlanbehandlinger {
    +nasjonalArealplanId: NasjonalArealplanId
    +inkluderPlandokumenter: boolean
}

FinnPlanbehandlinger -- NasjonalArealplanId

@enduml