@startuml
!include ./../no.ks.fiks.plan.v2.felles.planbehandling/planbehandling.pu

class FinnPlanbehandlingerResultat {
    +planbehandlinger: Planbehandling[]
}

FinnPlanbehandlingerResultat -- Planbehandling

@enduml