@startuml

class FinnPlaner {
    {field} Soekskriterie :  soekskriterie[]
}

class Soekskriterie {
    {field} Felt : soekskriterieFelt
    {field} Operator : soekskriterieOperator
    {field} Parameterverdier : String
}

enum SoekskriterieFelt {
    nasjonalArealplanId.kommunenummer
    nasjonalArealplanId.fylkesnummer
    nasjonalArealplanId.landkode
    nasjonalArealplanId.planidentifikasjon
    plantype.kodeverdi
    plannavn
    planstatus.kodeverdi
    plandokumentasjonOppdatert
    ubehandletKlage
    ubehandletInnsigelse
    vedtakEndeligPlandato
    lovreferanse.kodeverdi
    forslagstillertype
}

enum SoekskriterieOperator {
     equal
     notequal
     between
     lessthan
     lessequal
     greaterthan
     greaterequal
     inlist
}

FinnPlaner *-- Soekskriterie
Soekskriterie *-- SoekskriterieFelt
Soekskriterie *-- SoekskriterieOperator

@enduml
