@startuml
!include ./../no.ks.fiks.plan.v2.felles.saksnummer/saksnummer.pu
!include ./../no.ks.fiks.plan.v2.felles.flate/flate.pu

class MidlertidigForbud {
    +omraade: Flate
    +saksnummer: Saksnummer
    +avgjoerelsedato: date
    +pblTiltakForbudtype: PblTiltakForbudtype
    +gyldigTilDato: date
    +omraadenavn: string
}

MidlertidigForbud -- Flate
MidlertidigForbud -- Saksnummer
MidlertidigForbud -- PblTiltakForbudtype

class PblTiltakForbudtype <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

@enduml