@startuml
class Planbehandling {
    +posisjon: Posisjon
    +dato: date
    +saksnummer: Saksnummer
    +planbehandlingstype: Planbehandlingstype
    +navn: string
    +plandokumenter: Dokument[]
}

Planbehandling -- Posisjon
Planbehandling -- Saksnummer
Planbehandling -- Planbehandlingstype
Planbehandling -- Dokument

note top of Posisjon : Se detaljer i diagram for skjema 'no.ks.fiks.plan.v2.felles.posisjon'
note top of Saksnummer : Se detaljer i diagram for skjema 'no.ks.fiks.plan.v2.felles.saksnummer'
note top of Dokument : Se detaljer i diagram for skjema 'no.ks.fiks.plan.v2.felles.dokument'

class Planbehandlingstype <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

@enduml