@startuml
!include ./../no.ks.fiks.plan.v2.felles.arealplan/arealplan.pu
!include ./../no.ks.fiks.plan.v2.felles.nasjonalarealplanid/nasjonalarealplanid.pu

class HentRelatertePlanerResultat {
    +nasjonalArealplanId: NasjonalArealplanId
    +planrelasjoner: Planrelasjoner[]
}

class Planrelasjoner {
    +planforhold: Planforhold
    +arealplan: Arealplan
}

class Planforhold <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

HentRelatertePlanerResultat -- NasjonalArealplanId
HentRelatertePlanerResultat -- Planrelasjoner
Planrelasjoner -- Arealplan
Planrelasjoner -- Planforhold

@enduml