@startuml
!include ./../no.ks.fiks.plan.v2.felles.matrikkelnummer/matrikkelnummer.pu

class FinnMidlertidigeForbudMottiltakForMatrikkelenhet {
    +matrikkelnummer: Matrikkelnummer
}

FinnMidlertidigeForbudMottiltakForMatrikkelenhet -- Matrikkelnummer

@enduml