@startuml
!include ./../no.ks.fiks.plan.v2.felles.nasjonalarealplanid/nasjonalarealplanid.pu

class FinnMidlertidigeForbudMottiltakForPlan {
    +nasjonalArealplanId: NasjonalArealplanId
}

FinnMidlertidigeForbudMottiltakForPlan -- NasjonalArealplanId

@enduml