@startuml
!include ./../no.ks.fiks.plan.v2.felles.midlertidigforbud/midlertidigforbud.pu

class FinnMidlertidigeForbudMottiltakResultat {
    +midlertidigeForbud: MidlertidigForbud[]
}

FinnMidlertidigeForbudMottiltakResultat -- MidlertidigForbud

@enduml