@startuml
!include ./../no.ks.fiks.plan.v2.felles.saksnummer/saksnummer.pu
!include ./../no.ks.fiks.plan.v2.felles.dokument/dokument.pu
!include ./../no.ks.fiks.plan.v2.felles.nasjonalarealplanid/nasjonalarealplanid.pu

class OppdaterArealplan {
    +nasjonalArealplanId: NasjonalArealplanId
    +plannavn: string
    +plantype: Plantype
    +planstatus: Planstatus
    +lovreferanse: Lovreferanse
    +saksnummer: Saksnummer
    +forslagstillertype: ForslagstillerType
    +vedlegg: Dokument[]
}

class Plantype <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

class Planstatus <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

class Lovreferanse <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

class ForslagstillerType <<Kode>>{
    +kodeverdi: string
    +kodebeskrivelse: string
}

OppdaterArealplan -- NasjonalArealplanId
OppdaterArealplan -- Plantype
OppdaterArealplan -- Planstatus
OppdaterArealplan -- Lovreferanse
OppdaterArealplan -- ForslagstillerType
OppdaterArealplan -- Saksnummer
OppdaterArealplan -- Dokument

@enduml