@startuml
!include ./../no.ks.fiks.plan.v2.felles.midlertidigforbud/midlertidigforbud.pu

class RegistrerMidlertidigforbudmottiltak {
    +forbudOmraade: Midlertidigforbud
}

RegistrerMidlertidigforbudmottiltak -- Midlertidigforbud

@enduml