@startuml

Fagsystem -> Planregister: no.ks.fiks.plan.v2.oppdatering.arealplan.opprett

alt Opprett ok
...tom mottatt-melding...
Fagsystem <- Planregister: no.ks.fiks.plan.v2.oppdatering.arealplan.opprett.mottatt
...resultat-melding med innhold...
Fagsystem <- Planregister: no.ks.fiks.plan.v2.oppdatering.arealplan.opprett.resultat

else Feil: opprettsmeldingen var ikke korrekt
...feil-melding med innhold...

Fagsystem <- Planregister: no.ks.fiks.plan.v2.feilmelding.ugyldigforespoersel

else Feil: planregister fikk serverfeil
...feil-melding med innhold...

Fagsystem <- Planregister: no.ks.fiks.plan.v2.feilmelding.serverfeil

end
@enduml