@startuml
!include ./../no.ks.fiks.plan.v2.felles.nasjonalarealplanid/nasjonalarealplanid.pu

class HentRelatertePlaner {
    +nasjonalArealplanId: NasjonalArealplanId
}

HentRelatertePlaner -- NasjonalArealplanId

@enduml