@startuml
!include ./../no.ks.fiks.plan.v2.felles.arealformaalomraade/arealformaalomraade.pu

class HentFormaalResultat {
    +arealformaalOmraade: ArealformaalOmraade [0..1]
}

HentFormaalResultat -- "[0..1]" ArealformaalOmraade


@enduml