@startuml
!include ./../no.ks.fiks.plan.v2.felles.saksnummer/saksnummer.pu
!include ./../no.ks.fiks.plan.v2.felles.nasjonalarealplanid/nasjonalarealplanid.pu
!include ./../no.ks.fiks.plan.v2.felles.dokument/dokument.pu

class RegistrerPlanavgrensning {
    +nasjonalArealplanId: NasjonalArealplanId
    +saksnummer: Saksnummer
    +vedlegg: Dokument[]
}

RegistrerPlanavgrensning -- NasjonalArealplanId
RegistrerPlanavgrensning -- Saksnummer
RegistrerPlanavgrensning -- Dokument

@enduml