@startuml
!include ./../no.ks.fiks.plan.v2.felles.saksnummer/saksnummer.pu
!include ./../no.ks.fiks.plan.v2.felles.nasjonalarealplanid/nasjonalarealplanid.pu

class HentAktoerer {
    +saksnummer: Saksnummer
    +nasjonalArealplanId: NasjonalArealplanId
}

HentAktoerer -- Saksnummer
HentAktoerer -- NasjonalArealplanId

@enduml