@startuml

class RegistrerGjeldendePlandokumenter {
    +nasjonalArealplanId: NasjonalArealplanId
    +plandokumenter: Dokument[]
}

RegistrerGjeldendePlandokumenter -- NasjonalArealplanId
RegistrerGjeldendePlandokumenter -- Dokument

note top of NasjonalArealplanId : Se detaljer i diagram for skjema 'no.ks.fiks.plan.v2.felles.nasjonalarealplanid'
note top of Dokument : Se detaljer i diagram for skjema 'no.ks.fiks.plan.v2.felles.dokument'

@enduml