@startuml
!include ./../no.ks.fiks.plan.v2.felles.dokument/dokument.pu
!include ./../no.ks.fiks.plan.v2.felles.nasjonalarealplanid/nasjonalarealplanid.pu

class RegistrerGjeldendePlandokumenter {
    +nasjonalArealplanId: NasjonalArealplanId
    +plandokumenter: Dokument[]
}

RegistrerGjeldendePlandokumenter -- NasjonalArealplanId
RegistrerGjeldendePlandokumenter -- Dokument

@enduml