@startuml
!include ./../no.ks.fiks.plan.v2.felles.nasjonalarealplanid/nasjonalarealplanid.pu

class HentArealplan {
    +nasjonalArealplanId: NasjonalArealplanId
    +inkluderPlanbehandlinger: boolean
}

HentArealplan -- NasjonalArealplanId

@enduml