@startuml

class FinnDispensasjonerResultat {
    +dispensasjoner: Dispensasjon[]
}

FinnDispensasjonerResultat -- Dispensasjon

note top of Dispensasjon : Se detaljer i diagram for skjema 'no.ks.fiks.plan.v2.felles.dispensasjon'

@enduml