@startuml
!include ./../no.ks.fiks.plan.v2.felles.dispensasjon/dispensasjon.pu

class FinnDispensasjonerResultat {
    +dispensasjoner: Dispensasjon[]
}

FinnDispensasjonerResultat -- Dispensasjon

@enduml