@startuml
!include ./../no.ks.fiks.plan.v2.felles.nasjonalarealplanid/nasjonalarealplanid.pu

class HentPlanomraader {
    +nasjonalArealplanId: NasjonalArealplanId
}

HentPlanomraader -- NasjonalArealplanId

@enduml