@startuml

class RegistrerPlanbehandling {
    +nasjonalArealplanId: NasjonalArealplanId
    +planstatus: Planstatus
    +planbehandling: Planbehandling
}

class Planstatus {
    +kodeverdi: string
    +kodebeskrivelse: string
}

RegistrerPlanbehandling -- NasjonalArealplanId
RegistrerPlanbehandling -- Planstatus
RegistrerPlanbehandling -- Planbehandling

note top of NasjonalArealplanId : Se detaljer i diagram for skjema 'no.ks.fiks.plan.v2.felles.nasjonalarealplanid'
note top of Planbehandling : Se detaljer i diagram for skjema 'no.ks.fiks.plan.v2.felles.planbehandling'

@enduml