@startuml
!include ./../no.ks.fiks.plan.v2.felles.planbehandling/planbehandling.pu
!include ./../no.ks.fiks.plan.v2.felles.nasjonalarealplanid/nasjonalarealplanid.pu

class RegistrerPlanbehandling {
    +nasjonalArealplanId: NasjonalArealplanId
    +planstatus: Planstatus
    +planbehandling: Planbehandling
}

class Planstatus {
    +kodeverdi: string
    +kodebeskrivelse: string
}

RegistrerPlanbehandling -- NasjonalArealplanId
RegistrerPlanbehandling -- Planstatus
RegistrerPlanbehandling -- Planbehandling

@enduml