@startuml
!include ./../no.ks.fiks.plan.v2.felles.nasjonalarealplanid/nasjonalarealplanid.pu

class HentFormaal {
    +nasjonalArealplanId: NasjonalArealplanId
}

HentFormaal -- NasjonalArealplanId

@enduml