@startuml
class Arealplan {
    +nasjonalArealplanId: NasjonalArealplanId
    +plantype: Plantype
    +plannavn: string
    +planstatus: Planstatus
    +plandokumentasjonOppdatert: boolean
    +ubehandletKlage: boolean
    +ubehandletInnsigelse: boolean
    +vedtaksdato: date
    +vedtakEndeligPlanDato: date
    +lovreferanse: Lovreferanse
    +forslagstillerType: ForslagstillerType
    +alternativFinnes: boolean
}

Arealplan -- NasjonalArealplanId
Arealplan -- Plantype
Arealplan -- Planstatus
Arealplan -- Lovreferanse
Arealplan -- ForslagstillerType

note top of NasjonalArealplanId : Se detaljer i diagram for skjema 'no.ks.fiks.plan.v2.felles.nasjonalarealplanid'

class Plantype <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

class Planstatus <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

class Lovreferanse <<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

class ForslagstillerType <<Kode>>{
    +kodeverdi: string
    +kodebeskrivelse: string
}

@enduml