@startuml

class FinnArealplanerResultat {
    +arealplaner: Arealplan[]
}

FinnArealplanerResultat -- Arealplan

note top of Arealplan : Se detaljer i diagram for skjema 'no.ks.fiks.plan.v2.felles.arealplan'

@enduml